extends Control
class_name InventoryScreen
## InventoryScreen — the character sheet: equipment slots, belt potions, bag grid.
##
## Built in code rather than as a .tscn because the PWA's inventory was generated by
## 842 lines of string concatenation: the layout is driven entirely by DATA (how many
## belt rows the worn belt has, how many gem stacks exist), so a hand-authored scene
## would have to rebuild itself anyway. Code-built means one source of truth.
##
## Design rules taken from the PWA and Jan's stated preferences:
##   - flat, machine-like design: no cards, no rounded panels, no shadows
##   - NO hover/focus states — mobile game, state only on tap
##   - no emoji: every slot renders a real PNG from assets/items/
##   - slot borders carry the item's quality colour

const GameData := preload("res://scripts/data/game_data.gd")
const ItemGen := preload("res://scripts/items/item_gen.gd")
const UIKit := preload("res://scripts/ui/ui_kit.gd")

const CELL := 64
const GRID_COLUMNS := 5
const BAG_CELLS := 20
## 5 columns inside 358 - 32 (container) - 24 (wrap padding) - 4*6 (gaps) = 278 / 5.
## Class level rather than local to `_build`, because `_refresh_bag` rebuilds the cells
## and needs the same number — a local copy is how the two drift apart.
const BAG_CELL := 55.0

## Slot order and labels for the equipment panel. The label is what the empty slot
## shows; the icon underneath is the "placeholder" PNG the PWA used per slot.
const SLOT_LABELS := {
	"weapon": "Main Hand", "armor": "Armor", "helmet": "Helmet", "shield": "Off Hand",
	"ring1": "Ring 1", "ring2": "Ring 2", "amulet": "Amulet", "belt": "Belt",
	"gloves": "Gloves", "boots": "Boots",
}

const SLOT_PLACEHOLDER := {
	"weapon": "assets/items/weapon_iron_sword.png",
	"armor": "assets/items/armor_leather.png",
	"helmet": "assets/items/helmet_linen_hood.png",
	"shield": "assets/items/shield_wooden.png",
	"ring1": "assets/items/ring_copper.png",
	"ring2": "assets/items/ring_copper.png",
	"amulet": "assets/items/amulet_bone.png",
	"belt": "assets/items/belt_cloth.png",
	"gloves": "assets/items/gloves_leather.png",
	"boots": "assets/items/boots_boots.png",
}

## Quality colours, from the RARITY table. Unique is checked first because a unique
## item also has quality 'unique'; crafted overrides everything.
const QUALITY_FALLBACK := {
	"normal": Color("#888888"), "magic": Color("#4a7dff"),
	"rare": Color("#ffd700"), "unique": Color("#b8860b"),
}

signal item_tapped(inventory_index: int)
signal equip_slot_tapped(slot: String)
signal potion_slot_tapped(index: int)
## A socket cell was tapped: arm it (it must be empty) for the next gem tap.
signal socket_armed(host_id: String, socket_index: int)
## A gem in the panel was tapped: put it into the armed socket.
signal gem_tapped(host_id: String, gem_id: String)
signal back_pressed()

var _data: Node
var _gen: ItemGen
var _state

var _slot_nodes: Dictionary = {}     # slot name -> Button
var _bag_nodes: Array = []           # Button per bag cell
var _potion_nodes: Array = []
var _bag_grid: GridContainer
var _potion_row: HBoxContainer
var _socket_row: HBoxContainer
var _gem_row: HBoxContainer
var _socket_label: Label
var _stats_label: Label
var _gold_label: Label

## Which item the socket panel is showing. Set by tapping a bag cell, so the panel
## follows the player's selection rather than needing a dialog per item.
var _socket_host_id: String = ""
## Which socket the next gem tap will fill. -1 means none is armed yet.
var _armed_socket: int = -1


func _init(game_data: Node, gen: ItemGen, state) -> void:
	_data = game_data
	_gen = gen
	_state = state


func _ready() -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
	_build()
	refresh()


# --- construction ------------------------------------------------------------

## True when this screen is embedded as a tab of CharacterModal rather than shown as a
## page of its own. It changes two things, both of which the PWA does in CSS:
##
##  - `.modal-content .card { background:transparent; border:none; padding:0; margin:0 }`
##    and `.combined-screen.active #inventoryScreen { max-width:none; margin:0;
##    padding:0 4px }` — inside the dialog there is no page background and no page
##    padding, because the dialog IS the page.
##  - the PWA's inventory tab has no title row of its own; the `.combined-tabs` strip
##    already says which tab is open. The port's "Zpet do mesta" / "Inventar" header is
##    standalone-screen chrome and is dropped when embedded.
var _embedded := false


## Called by CharacterModal BEFORE the screen is added to the tree, because `_build()`
## runs from `_ready()` and has to branch on this.
func hide_chrome() -> void:
	_embedded = true


func _build() -> void:
	# The PWA's inventory is ONE scrolling column, not two side-by-side panels. A
	# 390px canvas cannot hold the equipment grid (3 x 75px + gaps = 237) beside a bag
	# grid (5 columns of >=64px = 340) — the old HBox laid out 740px of content on a
	# 390px screen, so the whole bag half was off-canvas and the screen read as empty.
	#
	# Embedded, there is no `screen_page`: that helper adds its own full-rect background
	# and its own ScrollContainer, and inside the modal the body already scrolls and the
	# dialog already paints black. A nested scroll container swallows drags.
	if _embedded:
		var inline := VBoxContainer.new()
		inline.set_anchors_preset(Control.PRESET_FULL_RECT)
		inline.add_theme_constant_override("separation", 8)
		add_child(inline)
		inline.add_child(_make_equipment_panel())
		inline.add_child(_make_bag_panel())
		return

	var page := UIKit.screen_page(self)
	var column: VBoxContainer = page["column"]
	column.add_theme_constant_override("separation", 6)

	column.add_child(_make_header())
	column.add_child(_make_equipment_panel())
	column.add_child(_make_bag_panel())


## Standalone chrome only — the "Zpet do mesta" button and the "Inventar" title. An
## embedded inventory drops this; `hide_chrome()` is what decides.
func _make_header() -> Control:
	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation", 8)

	var back := UIKit.back_button("Zpet do mesta")
	back.pressed.connect(func(): back_pressed.emit())
	column.add_child(back)

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 12)
	column.add_child(row)

	var title := UIKit.label("Inventar", 22, "#f0f0f0")
	title.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	title.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	row.add_child(title)

	var gold := UIKit.label("", 15, UIKit.GOLD, HORIZONTAL_ALIGNMENT_RIGHT)
	gold.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	row.add_child(gold)
	_gold_label = gold

	return column


## `.inv-equip-panel { display:grid; grid-template-columns:repeat(3, auto); gap:6px;
##                    justify-content:center }` — a PAPER DOLL, not an ordered list.
## The CSS pins every slot to a (row, column) pair:
##
##   #invSlotHelmet { grid-column:2; grid-row:1 }   #invSlotAmulet { grid-column:3; grid-row:1 }
##   #invSlotWeapon { grid-column:1; grid-row:2 }   #invSlotArmor  { grid-column:2; grid-row:2 }
##   #invSlotShield { grid-column:3; grid-row:2 }   #invSlotRing1  { grid-column:1; grid-row:3 }
##   #invSlotBelt   { grid-column:2; grid-row:3 }   #invSlotRing2  { grid-column:3; grid-row:3 }
##   #invSlotGloves { grid-column:1; grid-row:4 }   #invSlotBoots  { grid-column:3; grid-row:4 }
##
## Godot's GridContainer fills row-major and cannot place a child at a cell, so the grid
## is walked cell by cell with invisible fillers where the PWA has no slot.
##
## [row, column, slot, height] — columns and rows are ZERO-based here, one less than the
## CSS `grid-column`/`grid-row` values. `.inv-slot-square` is 75x75, `.inv-slot-tall`
## (the weapon) is 75x110, `.inv-slot-belt` is 75x48.
const DOLL: Array = [
	[0, 1, "helmet", 75.0],
	[0, 2, "amulet", 75.0],
	[1, 0, "weapon", 110.0],
	[1, 1, "armor", 75.0],
	[1, 2, "shield", 75.0],
	[2, 0, "ring1", 75.0],
	[2, 1, "belt", 48.0],
	[2, 2, "ring2", 75.0],
	[3, 0, "gloves", 75.0],
	[3, 2, "boots", 75.0],
]


func _make_equipment_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 6)

	var grid := GridContainer.new()
	grid.columns = 3
	grid.add_theme_constant_override("h_separation", 6)
	grid.add_theme_constant_override("v_separation", 6)
	# A GridContainer has no `alignment` property (only BoxContainer does); the paper
	# doll is centred by shrinking the grid to its own columns.
	grid.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	panel.add_child(grid)

	# Row-major walk. `_cursor` is the cell the next child lands in, which is the only
	# way to honour an explicit (row, column) table with a container that has no
	# placement API.
	var cursor := 0
	for entry in DOLL:
		var cell := int(entry[0]) * 3 + int(entry[1])
		while cursor < cell:
			grid.add_child(_filler())
			cursor += 1
		var slot := str(entry[2])
		var button := _make_slot_button(SLOT_LABELS.get(slot, slot), Vector2(75.0, float(entry[3])))
		# A slot that is shorter than its row (the belt) must not be stretched to the
		# row height: in the PWA `height:48px` wins over the grid's stretch.
		button.size_flags_vertical = Control.SIZE_SHRINK_BEGIN
		var slot_name := slot
		button.pressed.connect(func(): equip_slot_tapped.emit(slot_name))
		_slot_nodes[slot] = button
		grid.add_child(button)
		cursor += 1

	_stats_label = Label.new()
	_stats_label.add_theme_font_size_override("font_size", 13)
	_stats_label.add_theme_color_override("font_color", Color("#aaaaaa"))
	panel.add_child(_stats_label)

	var potion_title := Label.new()
	potion_title.text = "Belt"
	potion_title.add_theme_font_size_override("font_size", 14)
	panel.add_child(potion_title)

	# `.inv-potion-slots { display:grid; grid-template-columns:repeat(4, 36px); gap:2px;
	#                      justify-content:center }` — 36px cells, 2px gap.
	_potion_row = HBoxContainer.new()
	_potion_row.add_theme_constant_override("separation", 2)
	_potion_row.alignment = BoxContainer.ALIGNMENT_CENTER
	_potion_row.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	panel.add_child(_potion_row)

	return panel


## An empty paper-doll cell: the PWA's grid leaves the cell out entirely, but a
## GridContainer counts children, so an invisible spacer is what keeps column 3 in
## column 3.
func _filler() -> Control:
	var spacer := Control.new()
	spacer.custom_minimum_size = Vector2(75, 75)
	spacer.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return spacer


func _make_bag_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 6)

	var title := Label.new()
	title.text = "Batoh"
	title.add_theme_font_size_override("font_size", 14)
	panel.add_child(title)

	# `.inv-grid-wrap { background:#000; border:1px solid #333; border-radius:10px;
	#                  padding:12px }` — the bag grid lives in its own bordered box.
	var wrap := PanelContainer.new()
	var wrap_style := StyleBoxFlat.new()
	wrap_style.bg_color = Color("#000000")
	wrap_style.border_color = Color("#333333")
	wrap_style.set_border_width_all(1)
	wrap_style.set_corner_radius_all(10)
	wrap_style.content_margin_left = 12
	wrap_style.content_margin_right = 12
	wrap_style.content_margin_top = 12
	wrap_style.content_margin_bottom = 12
	wrap.add_theme_stylebox_override("panel", wrap_style)
	wrap.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	panel.add_child(wrap)

	_bag_grid = GridContainer.new()
	# `.inv-grid { grid-template-columns:repeat(5, 1fr); gap:6px }`
	_bag_grid.columns = GRID_COLUMNS
	_bag_grid.add_theme_constant_override("h_separation", 6)
	_bag_grid.add_theme_constant_override("v_separation", 6)
	_bag_grid.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	wrap.add_child(_bag_grid)

	# 5 columns inside 358 - 32 (container) - 24 (wrap padding) - 4*6 (gaps) = 278 / 5.
	# `UIKit.item_cell` owns the `.chest-cell` look (light #aaa fill, 25% when empty) —
	# in the PWA the bag and the chest grid are the SAME widget, and the port had them
	# diverge. The cells are REBUILT on refresh rather than restyled, the way the chest
	# screen does it: an empty cell and a filled one differ in fill, border, opacity and
	# children, and patching four of those into a live Button is how one of them gets
	# forgotten. That rebuild is `_refresh_bag`'s job; this only reserves the slots.
	for i in BAG_CELLS:
		_bag_nodes.append(null)

	# The socket panel: one row of sockets for the item currently selected, plus the
	# gems in the bag that may go into them. A separate panel rather than a modal
	# because the PWA's gem picker was a full overlay and Jan wants dialogs gone.
	var socket_title := Label.new()
	socket_title.text = "Sockets"
	socket_title.add_theme_font_size_override("font_size", 14)
	panel.add_child(socket_title)

	_socket_label = Label.new()
	_socket_label.add_theme_font_size_override("font_size", 12)
	_socket_label.add_theme_color_override("font_color", Color(UIKit.DIM))
	_socket_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	panel.add_child(_socket_label)

	_socket_row = HBoxContainer.new()
	_socket_row.add_theme_constant_override("separation", 4)
	panel.add_child(_socket_row)

	_gem_row = HBoxContainer.new()
	_gem_row.add_theme_constant_override("separation", 4)
	panel.add_child(_gem_row)

	return panel


## `.inv-equip-slot { background:#000; border:1.5px solid #4a4a4a; border-radius:8px }`
## and `.empty { border-style:dashed; background:#000 }` with the placeholder icon at
## opacity 0.25. No hover state — Jan's rule for a mobile screen: a tap is the only
## feedback (the PWA's `:hover` rules are desktop leftovers and are deliberately not
## ported).
func _make_slot_button(label: String, size: Vector2 = Vector2(CELL, CELL)) -> Button:
	var button := Button.new()
	button.custom_minimum_size = size
	# NOT `flat = true`: `flat` makes a Button skip drawing its stylebox entirely, so
	# every slot border in the PWA's inventory was invisible — items floated on the
	# background and empty slots did not exist at all. The border comes from the
	# stylebox overrides below, and `flat` silently disabled them.
	button.focus_mode = Control.FOCUS_NONE   # no focus ring on tap
	button.mouse_filter = Control.MOUSE_FILTER_STOP

	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#4a4a4a")
	style.set_border_width_all(2)
	style.set_corner_radius_all(8)
	for state_name in ["normal", "hover", "focus", "disabled"]:
		button.add_theme_stylebox_override(state_name, style)
	var pressed := style.duplicate()
	pressed.bg_color = Color("#111111")
	pressed.border_color = Color("#aaaaaa")
	button.add_theme_stylebox_override("pressed", pressed)

	return button


## A slot that holds nothing: the dashed border the PWA used for `.empty`. Kept as a
## separate style swap rather than a rebuild, because an empty slot and a filled one
## are the same Button with a different box.
func _set_empty_style(button: Button) -> void:
	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#4a4a4a")
	style.set_border_width_all(2)
	style.set_corner_radius_all(8)
	# `border-style:dashed` — Godot has no dashed border for a StyleBox, so the dashed
	# look comes from the dimmer colour plus the 25%-opacity placeholder icon. Drawing
	# dashes by hand per slot would be four draw calls per cell for one visual cue.
	style.border_color = Color("#3a3a3a")
	for state_name in ["normal", "hover", "focus", "disabled"]:
		button.add_theme_stylebox_override(state_name, style)
	var pressed := style.duplicate()
	pressed.bg_color = Color("#111111")
	button.add_theme_stylebox_override("pressed", pressed)


# --- rendering ---------------------------------------------------------------

## Rebuild everything from the current save. Called after every mutation, which is
## how the PWA worked and keeps this function the single place that knows the layout.
func refresh() -> void:
	_refresh_equipment()
	_refresh_potions()
	_refresh_bag()
	_refresh_sockets()
	_refresh_stats()


func _refresh_equipment() -> void:
	for slot in ItemGen.EQUIP_SLOTS:
		var button: Button = _slot_nodes[slot]
		var item_id: Variant = _state.equip().get(slot)
		# 'fists' is the implicit weapon: the slot reads as empty even though the id
		# is set, exactly as the PWA did.
		var is_empty: bool = item_id == null or item_id == "" or item_id == "fists"
		var item: Dictionary = {} if is_empty else _resolve(item_id)
		_set_slot_content(button, item, SLOT_PLACEHOLDER.get(slot, ""), is_empty)


func _refresh_potions() -> void:
	_state.sync_potion_slots(_find_item_callable())
	for child in _potion_row.get_children():
		child.queue_free()
	_potion_nodes.clear()

	var slots: Array = _state.equip().get("beltPotionSlots", [])
	for i in slots.size():
		# `.inv-potion-slot { width:36px; height:36px; border:2px solid #4a4a4a;
		#                     border-radius:4px }`
		var button := _make_slot_button("", Vector2(36, 36))
		var item_id: Variant = slots[i]
		var item: Dictionary = {} if item_id == null else _resolve(item_id)
		if item.is_empty():
			_set_empty_style(button)
			# Empty potion slots show a desaturated potion icon, never an emoji.
			_set_placeholder_icon(button, "assets/items/potion_healing_light.png", 0.25)
		else:
			_set_slot_content(button, item, "", false)
		button.pressed.connect(func(): potion_slot_tapped.emit(i))
		_potion_nodes.append(button)
		_potion_row.add_child(button)


func _refresh_bag() -> void:
	# Rebuild, like the chest does. `UIKit.item_cell` is the ONE definition of a
	# `.chest-cell`, so the bag cannot drift from the chest again.
	for child in _bag_grid.get_children():
		_bag_grid.remove_child(child)
		child.queue_free()
	_bag_nodes.clear()
	var inventory: Array = _state.inventory()
	for i in BAG_CELLS:
		var item: Dictionary = {}
		var count := 0
		if i < inventory.size():
			var entry: Variant = inventory[i]
			var item_id: String = entry.get("id", "") if entry is Dictionary else str(entry)
			item = _resolve(item_id)
			count = int(entry.get("count", 1)) if entry is Dictionary else 1
			if not item.is_empty() and count > 1:
				item = item.duplicate()
				item["count"] = count
		var cell := UIKit.item_cell(item, BAG_CELL, item.is_empty())
		# A tap equips (the router decides) but ALSO selects the item for the socket
		# panel — that is the whole reason no gem dialog is needed.
		var index := i
		cell.pressed.connect(func(): _on_bag_tapped(index))
		_bag_nodes.append(cell)
		_bag_grid.add_child(cell)


## One tap = one action, and the selection follows it. The router still gets the tap so
## equipping works; this only records which item the socket panel should show.
func _on_bag_tapped(index: int) -> void:
	var inventory: Array = _state.inventory()
	if index >= 0 and index < inventory.size():
		var entry: Variant = inventory[index]
		var item_id: String = str(entry.get("id", "")) if entry is Dictionary else str(entry)
		var item: Dictionary = _resolve(item_id)
		# Only a socketable item becomes the host; anything else clears the panel.
		if int(item.get("sockets", 0)) > 0:
			if _socket_host_id != item_id:
				_socket_host_id = item_id
				# A different host invalidates the armed socket index.
				_armed_socket = -1
		elif _socket_host_id == item_id:
			_socket_host_id = ""
			_armed_socket = -1
	item_tapped.emit(index)


## The socket panel: one cell per socket of the selected item, then the gems and
## jewels in the bag. Tapping an EMPTY socket arms it; tapping a gem fills the armed
## socket. That two-tap flow replaces the PWA's full-screen gem modal.
func _refresh_sockets() -> void:
	for child in _socket_row.get_children():
		child.queue_free()
	for child in _gem_row.get_children():
		child.queue_free()

	var host: Dictionary = _resolve(_socket_host_id)
	if host.is_empty():
		_socket_label.text = "Klepni na predmet v batohu pro vlozeni gemu."
		return
	var sockets := int(host.get("sockets", 0))
	if sockets <= 0:
		_socket_label.text = "%s nema socket." % str(host.get("name", _socket_host_id))
		return

	_socket_label.text = "%s - klepni na prazdny socket, pak na gem." % str(host.get("name", ""))
	var filled: Array = host.get("socketedGems", [])
	for i in sockets:
		var button := _make_slot_button("")
		button.custom_minimum_size = Vector2(44, 44)
		var record: Variant = filled[i] if i < filled.size() else null
		if record == null:
			_set_placeholder_icon(button, "assets/items/jewel_ruby.png", 0.22)
		else:
			var entry: Dictionary = record
			var gem_id := ""
			if str(entry.get("type", "")) == "jewel":
				gem_id = str(entry.get("jewelId", ""))
			_set_slot_content(button, _resolve(gem_id), "", gem_id == "")
		button.pressed.connect(func(): socket_armed.emit(_socket_host_id, i))
		_socket_row.add_child(button)

	# Gems and jewels from the bag, so the player can see what fits.
	var shown := 0
	for entry in _state.inventory():
		var item_id: String = str(entry.get("id", "")) if entry is Dictionary else str(entry)
		var item: Dictionary = _resolve(item_id)
		if str(item.get("type", "")) not in ["gem", "jewel"]:
			continue
		var gem_button := _make_slot_button("")
		gem_button.custom_minimum_size = Vector2(40, 40)
		_set_slot_content(gem_button, item, "", false)
		gem_button.pressed.connect(func(): gem_tapped.emit(_socket_host_id, item_id))
		_gem_row.add_child(gem_button)
		shown += 1
	if shown == 0:
		var hint := Label.new()
		hint.text = "V batohu neni zadny gem."
		hint.add_theme_font_size_override("font_size", 12)
		hint.add_theme_color_override("font_color", Color(UIKit.DIM))
		_gem_row.add_child(hint)


func _refresh_stats() -> void:
	var hero: Dictionary = _state.hero()
	var find := _find_item_callable()
	var max_hp := _gen.hero_max_hp(hero, _state.equip(), find)
	var max_mana := _gen.hero_max_mana(hero, _state.equip(), _state.data.get("heroClass", ""), find)
	var attrs := _gen.equip_attr_sum(_state.equip(), find, ["str", "vit", "dex", "int"])
	_stats_label.text = "Level %d   HP %d   Mana %d   STR %d  VIT %d  DEX %d  INT %d" % [
		int(hero["level"]), max_hp, max_mana,
		int(hero.get("attrStr", 0)) + int(attrs["str"]),
		int(hero.get("attrVit", 0)) + int(attrs["vit"]),
		int(hero.get("attrDex", 0)) + int(attrs["dex"]),
		int(hero.get("attrInt", 0)) + int(attrs["int"]),
	]
	# The gold readout is the nav/header's job, not a stat line's: at 390px the seven
	# stats plus gold overflow the right edge and get clipped. The PWA's `.inv-item-stats`
	# is 13px right-aligned text inside a panel; one line of stats is all that fits.
	_stats_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	if _gold_label != null:
		_gold_label.text = "%d zlata" % int(hero.get("gold", 0))


## One slot's contents: an icon (or a dimmed placeholder when empty) and a border in
## the item's quality colour.
func _set_slot_content(button: Button, item: Dictionary, placeholder: String, is_empty: bool) -> void:
	for child in button.get_children():
		child.queue_free()

	if item.is_empty():
		_set_empty_style(button)
		if placeholder != "":
			_set_placeholder_icon(button, placeholder, 0.25)
		return

	var icon := TextureRect.new()
	icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.texture = _load_texture(str(item.get("iconImg", "")))
	button.add_child(icon)
	_set_border(button, _quality_color(item))


func _set_placeholder_icon(button: Button, path: String, alpha: float) -> void:
	var icon := TextureRect.new()
	icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.texture = _load_texture(path)
	icon.modulate = Color(1, 1, 1, alpha)
	button.add_child(icon)


## Stack size badge, bottom-right, gold border — the PWA's `.cell-count`.
func _set_border(button: Button, colour: Color) -> void:
	var style: StyleBoxFlat = button.get_theme_stylebox("normal").duplicate()
	style.border_color = colour
	button.add_theme_stylebox_override("normal", style)
	button.add_theme_stylebox_override("pressed", style)
	button.add_theme_stylebox_override("hover", style)
	button.add_theme_stylebox_override("focus", style)


## Quality colour: unique and crafted override the plain quality string, matching
## getQualityColor() in the PWA.
func _quality_color(item: Dictionary) -> Color:
	if item.get("unique", false):
		return Color("#b8860b")
	if item.get("crafted", false):
		return Color("#ff8c00")
	var q: String = str(item.get("quality", item.get("rarity", "normal")))
	return QUALITY_FALLBACK.get(q, QUALITY_FALLBACK["normal"])


# --- resolvers ---------------------------------------------------------------

## An item id can be a static base (ITEMS), a generated gem, or a generated loot item
## on the save. All three must resolve, in that order of likelihood.
func _resolve(item_id: String) -> Dictionary:
	if item_id == "":
		return {}
	var static_item: Dictionary = _data.item(item_id)
	if not static_item.is_empty():
		return static_item
	# Gems are registered into the same index by game_data, so the lookup above
	# already covers them; anything left is a generated loot item.
	return _state.loot_item(item_id)


func _find_item_callable() -> Callable:
	return func(id): return _resolve(str(id))


func _load_texture(path: String) -> Texture2D:
	if path == "":
		return null
	var full := path if path.begins_with("res://") else "res://" + path
	if not ResourceLoader.exists(full):
		return null
	return load(full)
