extends MinSizeBox
class_name InventoryScreen
## InventoryScreen — the character sheet: equipment slots, belt potions, bag grid.
##
## Built in code rather than as a .tscn because the PWA's inventory was generated by
## 842 lines of string concatenation: the layout is driven entirely by DATA (how many
## belt rows the worn belt has, how many gem stacks exist), so a hand-authored scene
## would have to rebuild itself anyway. Code-built means one source of truth.
##
## Design rules taken from the PWA and Jan's stated preferences:
##   - flat, machine-like design: no cards, no rounded panels, no shadows
##   - NO hover/focus states — mobile game, state only on tap
##   - no emoji: every slot renders a real PNG from assets/items/
##   - slot borders carry the item's quality colour

const GameData := preload("res://scripts/data/game_data.gd")
const ItemGen := preload("res://scripts/items/item_gen.gd")
const UIKit := preload("res://scripts/ui/ui_kit.gd")
const ItemStats := preload("res://scripts/items/item_stats.gd")
const ItemInfoOverlay := preload("res://scripts/ui/item_info_overlay.gd")

const CELL := 64
const GRID_COLUMNS := 5
const BAG_CELLS := 20
## `.inv-potion-slots { grid-template-columns: repeat(4, 36px) }` — the belt row is FOUR
## columns wide, and a 2-row belt (beltRows 2 -> 8 slots) wraps into 2 rows. See the note
## on `_make_potion_panel`.
const POTION_COLUMNS := 4
## `(338 - 4*6) / 5 = 62.8` — the live PWA's own computed width, measured as
## `cols=62.8281px 62.8438px 62.8281px 62.8438px 62.8438px`. 338 is the `.inv-grid`
## inside `#invGridWrap` (364 wide, minus 1px border each side, minus 12px padding each
## side). The port hardcoded 55, so every cell was 8px narrow and the fifth one landed at
## x=313 instead of 301.
##
## It is a MINIMUM, not a fixed width: the cells also get SIZE_EXPAND_FILL, which is what
## makes a `GridContainer` behave like the CSS's `repeat(5, 1fr)` (equal columns that fill
## the row) instead of five fixed boxes bunched at the left.
const BAG_CELL := 62.8

## Slot order and labels for the equipment panel. The label is what the empty slot
## shows; the icon underneath is the "placeholder" PNG the PWA used per slot.
const SLOT_LABELS := {
	"weapon": "Main Hand", "armor": "Armor", "helmet": "Helmet", "shield": "Off Hand",
	"ring1": "Ring 1", "ring2": "Ring 2", "amulet": "Amulet", "belt": "Belt",
	"gloves": "Gloves", "boots": "Boots",
}

const SLOT_PLACEHOLDER := {
	"weapon": "assets/items/weapon_iron_sword.png",
	"armor": "assets/items/armor_leather.png",
	"helmet": "assets/items/helmet_linen_hood.png",
	"shield": "assets/items/shield_wooden.png",
	"ring1": "assets/items/ring_copper.png",
	"ring2": "assets/items/ring_copper.png",
	"amulet": "assets/items/amulet_bone.png",
	"belt": "assets/items/belt_cloth.png",
	"gloves": "assets/items/gloves_leather.png",
	"boots": "assets/items/boots_boots.png",
}

## Quality colours, from the RARITY table. Unique is checked first because a unique
## item also has quality 'unique'; crafted overrides everything.
const QUALITY_FALLBACK := {
	"normal": Color("#888888"), "magic": Color("#4a7dff"),
	"rare": Color("#ffd700"), "unique": Color("#b8860b"),
}

## A bag cell was tapped. The router equips through it only when the overlay is closed —
## the PWA shows the item info FIRST and equips from the overlay's button, so this signal
## is the fallback, not the main path.
signal item_tapped(inventory_index: int)
signal equip_slot_tapped(slot: String)
signal potion_slot_tapped(index: int)
## An overlay button was pressed: "equip"/"equip_mh"/"equip_oh"/"equip_r1"/"equip_r2"
## for a bag item, "unequip" for a worn one.
signal overlay_action(action: String, slot: String)
## A socket was tapped: arm it (it must be empty) for the next gem tap.
signal socket_armed(host_id: String, socket_index: int)
## A gem in the overlay was tapped: put it into the armed socket.
signal gem_tapped(host_id: String, gem_id: String)
signal back_pressed()

var _data: Node
var _gen: ItemGen
var _state

var _slot_nodes: Dictionary = {}     # slot name -> Button
var _bag_nodes: Array = []           # Button per bag cell
var _potion_nodes: Array = []
var _bag_grid: GridContainer
var _potion_row: GridContainer
## The PWA shows a selected item's detail — stats, the compare block, its sockets and the
## gems that fit — in `#invItemOverlay`, a tap-through overlay OUTSIDE `#inventoryScreen`.
## The port had it as a permanent "Sockets" block at the bottom of the pane, which is
## invented state: the live pane has exactly three children (doll, potions, bag) and the
## extra block moved every real element below it.
##
## The socket-only panel it grew into afterwards was still wrong: it had no stats, no
## compare and no equip button, so tapping an item showed nothing a player reads an item
## for. `ItemInfoOverlay` is the whole thing, and it is a sibling here on purpose — it is
## an overlay, not a fourth block in the column.
var _item_overlay: ItemInfoOverlay
## The standalone (non-embedded) header's gold readout. Only the page form draws it; inside
## the modal there is no header at all, which is why the PWA's tab has no gold line.
var _gold_label: Label

## Which item the socket panel is showing. Set by tapping a bag cell, so the panel
## follows the player's selection rather than needing a dialog per item.
var _socket_host_id: String = ""
## Which socket the next gem tap will fill. -1 means none is armed yet.
var _armed_socket: int = -1
## The PWA's `_invSelectedIdx` / `_invSelectedSlot`: which cell the overlay is showing.
## They drive the `.selected` gold border and are cleared together (`clearSelection()`).
var _selected_bag: int = -1
var _selected_slot: String = ""


func _init(game_data: Node, gen: ItemGen, state) -> void:
	_data = game_data
	_gen = gen
	_state = state


func _ready() -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
	_build()
	# The overlay is built here but added by `mount_overlay()` to the DIALOG, not to this
	# pane. It matters: the PWA's `#invItemOverlay` is a SIBLING of `#inventoryScreen` at
	# `z-index:1000`, and the inventory pane is asserted to hold exactly the PWA's three
	# blocks. A fourth child here is invented state AND it would be clipped by the pane's
	# own box, so a full-screen overlay could never reach the screen edges.
	_item_overlay = ItemInfoOverlay.new(_data, _gen, _state, _find_item_callable(),
		ItemGen.EQUIP_SLOTS)
	_item_overlay.action.connect(func(a, s): overlay_action.emit(a, s))
	_item_overlay.dismissed.connect(_on_overlay_dismissed)
	_item_overlay.socket_tapped.connect(_on_socket_cell_tapped)
	_item_overlay.gem_tapped.connect(_on_gem_cell_tapped)
	refresh()


## Hand the overlay to whoever owns the full-screen dialog. `CharacterModal` calls this
## with its own root, so the overlay covers the dialog and the game world under it and is
## not a child of the inventory pane.
func mount_overlay(host: Control) -> void:
	if _item_overlay != null and _item_overlay.get_parent() == null:
		host.add_child(_item_overlay)


# --- construction ------------------------------------------------------------

## True when this screen is embedded as a tab of CharacterModal rather than shown as a
## page of its own. It changes two things, both of which the PWA does in CSS:
##
##  - `.modal-content .card { background:transparent; border:none; padding:0; margin:0 }`
##    and `.combined-screen.active #inventoryScreen { max-width:none; margin:0;
##    padding:0 4px }` — inside the dialog there is no page background and no page
##    padding, because the dialog IS the page.
##  - the PWA's inventory tab has no title row of its own; the `.combined-tabs` strip
##    already says which tab is open. The port's "Zpet do mesta" / "Inventar" header is
##    standalone-screen chrome and is dropped when embedded.
var _embedded := false


## Called by CharacterModal BEFORE the screen is added to the tree, because `_build()`
## runs from `_ready()` and has to branch on this.
func hide_chrome() -> void:
	_embedded = true


func _build() -> void:
	# The PWA's inventory is ONE scrolling column, not two side-by-side panels. A
	# 390px canvas cannot hold the equipment grid (3 x 75px + gaps = 237) beside a bag
	# grid (5 columns of >=64px = 340) — the old HBox laid out 740px of content on a
	# 390px screen, so the whole bag half was off-canvas and the screen read as empty.
	#
	# Embedded, there is no `screen_page`: that helper adds its own full-rect background
	# and its own ScrollContainer, and inside the modal the body already scrolls and the
	# dialog already paints black. A nested scroll container swallows drags.
	#
	# ⚠️ The PWA's `#inventoryScreen` holds EXACTLY THREE children and this column must
	# hold the same three. Measured on the live pane (`probe_pane_pwa.py inventory`):
	#   div.inv-equip-panel   [13,112 364x326]  margin 12px 0
	#   div.inv-potion-slots  [13,450 364x36]   margin 4px 0
	#   div.inv-grid-wrap     [13,494 364x295]  margin 8px 0
	# Everything the port added on top of those three — a "Batoh" heading, a "Belt"
	# heading, a "Sockets" heading with its socket/gem rows and a Level/HP/STR stat
	# line — is INVENTED state, and invented state is the biggest visual diff there is:
	# it moved every real element below it. The PWA's item detail (including socketing)
	# is the `#invItemOverlay`, a tap-through overlay, not a permanent block.
	if _embedded:
		var inline := VBoxContainer.new()
		inline.set_anchors_preset(Control.PRESET_FULL_RECT)
		# The three children carry the PWA's own MARGINS and the column adds no
		# separation: the PWA's `margin:12px 0` / `4px 0` / `8px 0` COLLAPSE between
		# adjacent siblings (max, not sum), which a `VBoxContainer` cannot express.
		# Measured on the live pane: doll bottom 438 -> potion top 450 (12), potion
		# bottom 486 -> wrap top 494 (8), wrap bottom 789 -> pane bottom 797 (8).
		# Emulated as 12/0, 8/0, 8/8 with separation 0, which gives exactly 12, 8, 8.
		inline.add_theme_constant_override("separation", 0)
		add_child(inline)
		inline.add_child(_margined(_make_equipment_panel(), 12.0, 0.0))
		# ⚠️ 12, NOT 8. The PWA's margins COLLAPSE to `max(m1, m2)`: `.inv-equip-panel` is
		# `margin:12px 0` and `.inv-potion-slots` is `margin:4px 0`, so the gap between the
		# doll's bottom edge and the belt row is `max(12, 4) = 12`. MEASURED on the live pane:
		# equip bottom 436.2 -> potion top 448.2. A `VBoxContainer` adds separations instead
		# of collapsing them, so the only way to say 12 is to put the whole 12 on ONE of the
		# two boxes — and the port carried 8 here, which put the belt row 4px high and every
		# block under it with it.
		inline.add_child(_margined(_make_potion_panel(), 12.0, 0.0))
		inline.add_child(_margined(_make_bag_panel(), 8.0, 8.0))
		return

	var page := UIKit.screen_page(self)
	var column: VBoxContainer = page["column"]
	column.add_theme_constant_override("separation", 6)

	# The standalone page form (only reachable if something shows the inventory as a
	# SCREEN, which the PWA never does — `inventory` is a modal tab). Same three blocks in
	# the same order, with the page header on top.
	column.add_child(_make_header())
	column.add_child(_margined(_make_equipment_panel(), 12.0, 0.0))
	column.add_child(_margined(_make_potion_panel(), 8.0, 0.0))
	column.add_child(_margined(_make_bag_panel(), 8.0, 8.0))


## Standalone chrome only — the "Zpet do mesta" button and the "Inventar" title. An
## embedded inventory drops this; `hide_chrome()` is what decides.
func _make_header() -> Control:
	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation", 8)

	var back := UIKit.back_button("Zpet do mesta")
	back.pressed.connect(func(): back_pressed.emit())
	column.add_child(back)

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 12)
	column.add_child(row)

	var title := UIKit.label("Inventar", 22, "#f0f0f0")
	title.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	title.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	row.add_child(title)

	var gold := UIKit.label("", 15, UIKit.GOLD, HORIZONTAL_ALIGNMENT_RIGHT)
	gold.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	row.add_child(gold)
	_gold_label = gold

	return column


## `.inv-equip-panel { display:grid; grid-template-columns:repeat(3, auto); gap:6px;
##                    justify-content:center }` — a PAPER DOLL, not an ordered list.
## The CSS pins every slot to a (row, column) pair:
##
##   #invSlotTownPortal { grid-column:1; grid-row:1 }   #invSlotHelmet { grid-column:2; grid-row:1 }
##   #invSlotAmulet { grid-column:3; grid-row:1 }
##   #invSlotWeapon { grid-column:1; grid-row:2 }       #invSlotArmor  { grid-column:2; grid-row:2 }
##   #invSlotShield { grid-column:3; grid-row:2 }
##   #invSlotRing1  { grid-column:1; grid-row:3 }       #invSlotBelt   { grid-column:2; grid-row:3 }
##   #invSlotRing2  { grid-column:3; grid-row:3 }
##   #invSlotGloves { grid-column:1; grid-row:4 }       #invSlotBoots  { grid-column:3; grid-row:4 }
##
## Godot's GridContainer fills row-major and cannot place a child at a cell, so the grid
## is walked cell by cell with invisible fillers where the PWA has no slot.
##
## [row, column, slot, width, height] — columns and rows are ZERO-based here, one less than
## the CSS `grid-column`/`grid-row` values. EVERY SIZE IS MEASURED off the live PWA via
## `tools/import/probe_equip_pwa.py`, because the CSS is content-box and the slot classes
## differ: `.inv-slot-square` 75x75, `.inv-slot-tall` 75x110, **`.inv-slot-small` 48x48**
## (the amulet and both rings — the port drew them 75x75), `.inv-slot-belt` 75x48 and
## `.inv-slot-tp` 48x48 (the town portal, which the port did not draw AT ALL).
## Getting these wrong is the "itemy byly větší než equip sloty" report: a 48px slot with a
## 75px cell's icon in it overflows its own border.
## `#invSlotTownPortal/#invSlotWeapon/#invSlotRing1 { justify-self:end }`,
## `#invSlotShield/#invSlotGloves { justify-self:start }`, everything else `stretch`.
## Read out of `style.css` line by line; a 48px slot in a 75px column needs to know which
## edge it hugs, and guessing "centre" put the two rings 13px off their column's edge.
const JUSTIFY_SELF := {
	"townPortal": "end", "weapon": "end", "ring1": "end",
	"shield": "start", "gloves": "start",
}

const DOLL: Array = [
	[0, 0, "townPortal", 48.0, 48.0],
	[0, 1, "helmet", 75.0, 75.0],
	[0, 2, "amulet", 48.0, 48.0],
	[1, 0, "weapon", 75.0, 110.0],
	[1, 1, "armor", 75.0, 110.0],
	[1, 2, "shield", 75.0, 110.0],
	[2, 0, "ring1", 48.0, 48.0],
	[2, 1, "belt", 75.0, 48.0],
	[2, 2, "ring2", 48.0, 48.0],
	[3, 0, "gloves", 75.0, 75.0],
	[3, 2, "boots", 75.0, 75.0],
]


## `.inv-equip-panel { display:grid; gap:6px; margin:12px 0; justify-content:center;
##                    grid-template-columns:repeat(3, auto); width:100% }`.
##
## The column widths are `auto`, i.e. the widest item in each column: 75px for columns 1
## and 3 (weapon/gloves and amulet/ring2/boots) and 75px for column 2. Measured live:
## `cols=75px 75px 75px`, the grid itself 237 wide and CENTRED (`justify-content:center`)
## with its first cell at x=77 — not at the pane's left edge.
##
## `justify-self` is per slot and it is what makes the doll look symmetric, because the
## 48px slots do not fill their 75px column:
##   townPortal / weapon / ring1 -> `end`      (right edge of the column)
##   shield / gloves             -> `start`    (left edge)
##   everything else             -> stretch (75px slot fills the column)
## The port centred every small slot, which put the rings 13px off and made the "ring
## column" read as a wobbly vertical line instead of one aligned edge.
func _make_equipment_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 0)
	# `.inv-equip-panel { width:100%; justify-content:center }` — the grid is centred by
	# its own `size_flags`, the panel spans the full body width.
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL

	var grid := GridContainer.new()
	grid.columns = 3
	grid.add_theme_constant_override("h_separation", 6)
	grid.add_theme_constant_override("v_separation", 6)
	# A GridContainer has no `alignment` property (only BoxContainer does); the paper
	# doll is centred by shrinking the grid to its own columns.
	grid.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	panel.add_child(grid)

	# Row-major walk. `_cursor` is the cell the next child lands in, which is the only
	# way to honour an explicit (row, column) table with a container that has no
	# placement API.
	var cursor := 0
	for entry in DOLL:
		var cell := int(entry[0]) * 3 + int(entry[1])
		while cursor < cell:
			grid.add_child(_filler())
			cursor += 1
		var slot := str(entry[2])
		# Each slot carries its OWN measured size (`[row, col, slot, width, height]`).
		var button := _make_slot_button(SLOT_LABELS.get(slot, slot),
			Vector2(float(entry[3]), float(entry[4])))
		# ⚠️  `align-items` DEFAULTS TO `stretch` IN CSS, BUT A FIXED HEIGHT TURNS THAT INTO
		# `start`. `.inv-equip-slot` has no `align-self`, so every slot inherits the grid's
		# `align-items:stretch` — and `.inv-slot-small { height:48px }` is a fixed height, so
		# stretch cannot stretch it and the browser places it at the ROW'S TOP. The port's
		# `SIZE_SHRINK_CENTER` centred it instead: MEASURED, the amulet came out at y=123.2
		# against the PWA's 110.2 (exactly `(75 - 48) / 2`) and the town portal with it. Two
		# of the three rows are 48 tall so the bug is invisible there, which is why it
		# survived — the top row is 75 and it is the one that shows.
		button.size_flags_vertical = Control.SIZE_SHRINK_BEGIN
		# `justify-self` per the CSS above. Its DEFAULT is `stretch` too, and a FIXED WIDTH
		# makes that behave as `start` as well: `#invSlotAmulet { grid-column:3 }` has no
		# `justify-self` and is still only 48 wide, so it sits on the column's LEFT edge.
		# The port stretched it to the full 75px column. MEASURED: amulet and ring2 both
		# came out 75 wide at x=237.9 where the PWA has 48 at 238.5. A slot whose width
		# EQUALS the column (75) is unaffected — start and stretch agree there — so only the
		# 48px slots need the distinction, and they are exactly the ones the map lists.
		match str(JUSTIFY_SELF.get(slot, "start")):
			"end":
				button.size_flags_horizontal = Control.SIZE_SHRINK_END
			"start":
				button.size_flags_horizontal = Control.SIZE_SHRINK_BEGIN
			_:
				button.size_flags_horizontal = Control.SIZE_FILL
		var slot_name := slot
		button.pressed.connect(func(): _on_equip_slot_pressed(slot_name))
		_slot_nodes[slot] = button
		grid.add_child(button)
		cursor += 1

	return panel


## `.inv-potion-slots { display:grid; grid-template-columns:repeat(4, 36px); gap:2px;
##                      margin:4px 0; justify-content:center }` — its own element in the
## PWA, NOT part of the doll panel, and `justify-content:center` centres the 4x36+3x2 =
## 150px block in the 364px pane (measured: first slot at x=120, i.e. (364-150)/2 = 107
## plus the 13px pane offset).
##
## ⚠️  It is FOUR COLUMNS, not a single row — and the belt decides how many rows there
## are. With no belt the PWA renders 4 slots (one row, 36 tall); with `belt_sash`
## (`beltRows: 2`) it renders EIGHT slots in **4 columns x 2 rows** and the block is
## **74 tall** (36 + gap 2 + 36). Measured on the live PWA with a worn sash:
## `.inv-potion-slots [12.9, 448.2, 364.2, 74]`, and the grid wrap below it starts at
## y=530.2. A single `HBoxContainer` put all eight in one row, so the potion block was
## 36 tall instead of 74 and the whole bag grid sat **44px too high**.
##
## The PWA's own `getTotalPotionSlots()` is `belt ? beltRows * 4 : 4`, which the port's
## `GameState.total_potion_slots` already matches — only the SHAPE was wrong here.
func _make_potion_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 0)
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_potion_row = GridContainer.new()
	_potion_row.columns = POTION_COLUMNS
	_potion_row.add_theme_constant_override("h_separation", 2)
	_potion_row.add_theme_constant_override("v_separation", 2)
	# `justify-content:center`: the block is its OWN minimum (4x36 + 3x2 = 150) and sits in
	# the middle of the 364px pane, measured on the live PWA as first slot x=120. SHRINK
	# CENTER is the direct equivalent — without it the grid stretches to the pane's full
	# width and the four slots sit hard left at x=12.
	_potion_row.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	panel.add_child(_potion_row)
	return panel


## A wrapper adding the PWA's own vertical MARGIN to one of the pane's children.
##
## A CSS margin on a block inside a plain block container does not collapse with a
## sibling's own margin unless they actually touch, and the PWA's three children use
## `max(m1, m2)`: measured doll->potion 12px (12 vs 4), potion->wrap 8px (8 vs 4),
## wrap->bottom 8px. A `VBoxContainer` separation is ADDED, so the only way to express
## the real numbers is to put the gaps on the boxes and keep the separation at 0.
class _Margined extends Container:
	var top := 0.0
	var bottom := 0.0
	var _child: Control

	func setup(child: Control, top_px: float, bottom_px: float) -> void:
		add_child(child)
		_child = child
		top = top_px
		bottom = bottom_px
		child.size_flags_horizontal = Control.SIZE_EXPAND_FILL

	func _get_minimum_size() -> Vector2:
		if _child == null:
			return Vector2.ZERO
		var inner := _child.get_combined_minimum_size()
		return Vector2(inner.x, inner.y + top + bottom)

	func _notification(what: int) -> void:
		if what == NOTIFICATION_SORT_CHILDREN and _child != null:
			fit_child_in_rect(_child, Rect2(Vector2(0.0, top), Vector2(size.x, size.y - top - bottom)))


func _margined(child: Control, top_px: float, bottom_px: float) -> Control:
	var box := _Margined.new()
	box.setup(child, top_px, bottom_px)
	return box


## An empty paper-doll cell: the PWA's grid leaves the cell out entirely, but a
## GridContainer counts children, so an invisible spacer is what keeps column 3 in
## column 3.
func _filler() -> Control:
	var spacer := Control.new()
	spacer.custom_minimum_size = Vector2(75, 75)
	spacer.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return spacer


## `.inv-potion-slots { display:grid; grid-template-columns:repeat(4, 36px); gap:2px;
##                      margin:4px 0; justify-content:center }` — 36px cells, 2px gap, and
## the PWA's `* { box-sizing:border-box }` means the 2px border is INSIDE the 36, not
## outside it. This is the ONLY content between the doll and the bag in the PWA; the
## "Belt" heading the port drew above it pushed the bag grid 23px down.
func _make_bag_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 0)
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL

	# `.inv-grid-wrap { max-height:200px; overflow-y:auto; margin:8px 0;
	#                  background:#000; border:1px solid #333; border-radius:10px;
	#                  padding:12px; box-sizing:border-box }` — but `#invGridWrap`
	# (the inventory's own id) overrides it with `max-height:none; padding:12px`.
	# Measured live: `div.inv-grid-wrap [13,494 364x295]` with `div.inv-grid [26,507 338x269]`
	# inside it — 364 - 2 (border) - 24 (padding) = 338, the grid's own width. A Godot
	# `PanelContainer` measures `content_margin` from INSIDE its border, so `12` here is
	# already the CSS's 12px padding and the 338 follows. The port's grid had come out 350
	# because the panel's stylebox did not carry the border width when the margin was
	# applied; assert the built width, do not eyeball it.
	var wrap := PanelContainer.new()
	var wrap_style := StyleBoxFlat.new()
	wrap_style.bg_color = Color("#000000")
	wrap_style.border_color = Color("#333333")
	wrap_style.set_border_width_all(1)
	wrap_style.set_corner_radius_all(10)
	# The panel's content margin is measured from INSIDE its border in Godot, so 12 is
	# already the PWA's 12px padding. `_filler()`'s cells carry the grid.
	#
	# ⚠️ 12 IS NOT THE FAITHFUL VALUE — it is 12 + the 1px border. MEASURED: with 12 the
	# grid came out **340 x 24.9**, against the PWA's **338.2 x 25.9**, i.e. 2px too wide and
	# 1px too far left, exactly one border width on each side. This is the same trap as the
	# tab strip's bottom margin: a `StyleBoxFlat` draws its border OUTSIDE the content margin,
	# so a CSS box whose padding sits inside its border must add that border here.
	wrap_style.content_margin_left = 13
	wrap_style.content_margin_right = 13
	wrap_style.content_margin_top = 13
	wrap_style.content_margin_bottom = 13
	wrap.add_theme_stylebox_override("panel", wrap_style)
	wrap.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	panel.add_child(wrap)

	_bag_grid = GridContainer.new()
	# `.inv-grid { display:grid; grid-template-columns:repeat(5, 1fr); gap:6px }`
	_bag_grid.columns = GRID_COLUMNS
	_bag_grid.add_theme_constant_override("h_separation", 6)
	_bag_grid.add_theme_constant_override("v_separation", 6)
	_bag_grid.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	# ⚠️  A `GridContainer` COMPUTES ITS MINIMUM IN WHOLE PIXELS: four rows of a 62.8px cell
	# plus three 6px gaps are 269.2, and the grid reported **266** (4 x 62 + 18), i.e. the
	# fractional part is dropped ONCE PER ROW. MEASURED: the port's rows landed 68.0 apart
	# against the PWA's 68.8, so each row after the first sat 0.8px high and the last one
	# 2.4px — a 4 790-pixel band of drift at rows 679-828 that no cell-level check can see
	# (every individual cell is the right size; the PITCH is wrong). The PWA's grid is
	# 269.4, so pin the grid's own minimum and let the rows divide it — which is what the
	# browser does with `grid-template-rows` on a 269.4-tall box.
	_bag_grid.custom_minimum_size = Vector2(0, 269)
	wrap.add_child(_bag_grid)

	# 338px of grid, 4 gaps of 6px = 24, leaves 314 / 5 = 62.8 per cell — which is what
	# the live PWA computes (`cols=62.8281px 62.8438px ...`). The port hardcoded 55 and
	# drew every cell 8px narrower with the row ending 40px short of the wrap.
	for i in BAG_CELLS:
		_bag_nodes.append(null)

	return panel


## `.inv-equip-slot { background:#000; border:1.5px solid #4a4a4a; border-radius:8px;
##                    overflow:hidden }` and `.empty { border-style:dashed; background:#000 }`
## with the placeholder icon at opacity 0.25. No hover state — Jan's rule for a mobile
## screen: a tap is the only feedback (the PWA's `:hover` rules are desktop leftovers and
## are deliberately not ported).
##
## ⚠️ `overflow:hidden` IS THE POINT, and it was missing. Godot does NOT clip a Button's
## children unless `clip_contents` is set, so an icon that reached the slot's edge drew
## over the border and past the rounded corner — the "the icon looks like a picture
## pasted into the slot with its own edge" report. Measured on the live PWA: the slot is
## 75px with `overflow:hidden`, and its `<img>` is EXACTLY the content box (73px), so the
## art can never cross the border there.
##
## The border is 1px, not 2px: `probe_slots_live.py` reads
## `border: 1px rgb(74,74,74)` on every slot of the live build.
##
## ⚠️ And the SIZE is the CSS size, NOT the CSS size minus the border. The comment here
## used to claim "Godot draws a stylebox border OUTSIDE the content box, so the minimum
## goes DOWN by 2" — that is WRONG, and it made every slot in the inventory 2px short on
## each axis. Measured on a bare Button with a 1px StyleBoxFlat and nothing else
## (`tools/probe_border_box.gd`): `custom_minimum_size = 75` draws 75x75, and
## `custom_minimum_size = 73` draws 73x73. The border is INSIDE, so subtracting it
## double-counts the same way the PWA's `box-sizing:border-box` does not.
##
## The visible symptom was the doll: the tall row came out 108 instead of 110, so the doll
## was 320 tall against the PWA's 326 and every block below it sat 6px high.
const SLOT_BORDER := 1.0


func _make_slot_button(label: String, size: Vector2 = Vector2(CELL, CELL)) -> Button:
	var button := Button.new()
	# The CSS box IS the drawn box — see the note on SLOT_BORDER. `box-sizing:border-box`
	# and Godot's stylebox agree; subtracting the border was the bug.
	button.custom_minimum_size = size
	# `overflow:hidden`. Without it every icon child draws over the slot's own border.
	button.clip_contents = true
	# NOT `flat = true`: `flat` makes a Button skip drawing its stylebox entirely, so
	# every slot border in the PWA's inventory was invisible — items floated on the
	# background and empty slots did not exist at all. The border comes from the
	# stylebox overrides below, and `flat` silently disabled them.
	button.focus_mode = Control.FOCUS_NONE   # no focus ring on tap
	button.mouse_filter = Control.MOUSE_FILTER_STOP

	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#4a4a4a")
	style.set_border_width_all(int(SLOT_BORDER))
	style.set_corner_radius_all(8)
	style.set_content_margin_all(0)
	for state_name in ["normal", "hover", "focus", "disabled"]:
		button.add_theme_stylebox_override(state_name, style)
	var pressed := style.duplicate()
	pressed.bg_color = Color("#111111")
	pressed.border_color = Color("#aaaaaa")
	button.add_theme_stylebox_override("pressed", pressed)

	return button


## A slot that holds nothing: the dashed border the PWA used for `.empty`. Kept as a
## separate style swap rather than a rebuild, because an empty slot and a filled one
## are the same Button with a different box.
func _set_empty_style(button: Button) -> void:
	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#3a3a3a")
	style.set_border_width_all(int(SLOT_BORDER))
	style.set_corner_radius_all(8)
	style.set_content_margin_all(0)
	# `border-style:dashed` — Godot has no dashed border for a StyleBox, so the dashed
	# look comes from the dimmer colour plus the 25%-opacity placeholder icon. Drawing
	# dashes by hand per slot would be four draw calls per cell for one visual cue.
	for state_name in ["normal", "hover", "focus", "disabled"]:
		button.add_theme_stylebox_override(state_name, style)
	var pressed := style.duplicate()
	pressed.bg_color = Color("#111111")
	button.add_theme_stylebox_override("pressed", pressed)


# --- rendering ---------------------------------------------------------------

## Rebuild everything from the current save. Called after every mutation, which is
## how the PWA worked and keeps this function the single place that knows the layout.
func refresh() -> void:
	_refresh_equipment()
	_refresh_potions()
	_refresh_bag()
	# `_refresh_sockets` rebuilds the OVERLAY's socket row, not a pane child: the pane
	# keeps the PWA's three children exactly.
	_refresh_sockets()
	# A refresh can land while the overlay is open (an equip, a socket insert). Its
	# contents are built from the item dictionary, so a host that changed identity has to
	# be re-read — otherwise the overlay shows the previous item's stats.
	if _item_overlay != null and _item_overlay.visible:
		var live := _resolve(_item_overlay.current_item_id())
		if not live.is_empty():
			_item_overlay._item = live


func _refresh_equipment() -> void:
	for slot in ItemGen.EQUIP_SLOTS:
		var button: Button = _slot_nodes[slot]
		var item_id: Variant = _state.equip().get(slot)
		# 'fists' is the implicit weapon: the slot reads as empty even though the id
		# is set, exactly as the PWA did.
		var is_empty: bool = item_id == null or item_id == "" or item_id == "fists"
		var item: Dictionary = {} if is_empty else _resolve(item_id)
		_set_slot_content(button, item, SLOT_PLACEHOLDER.get(slot, ""), is_empty)


func _refresh_potions() -> void:
	_state.sync_potion_slots(_find_item_callable())
	# ⚠️  `remove_child` + `free`, NOT `queue_free`: a deferred free leaves the child in
	# the tree until the end of the frame, so a refresh that runs twice in one frame (or
	# a test that refreshes in a loop) APPENDS to the previous slots instead of replacing
	# them — measured as 76 buttons where the PWA has 4. `_refresh_potions` is called from
	# the modal's own refresh path and from `show_screen`, so this is reachable in a real
	# session, not only in a test.
	for child in _potion_row.get_children():
		_potion_row.remove_child(child)
		child.free()
	_potion_nodes.clear()

	var slots: Array = _state.equip().get("beltPotionSlots", [])
	# `.inv-potion-slot { width:36px; height:36px; border:2px solid #4a4a4a;
	#                     border-radius:4px }` with `* { box-sizing:border-box }`, so the
	# 36 INCLUDES the border — and so does Godot's stylebox (see SLOT_BORDER). The old
	# comment here claimed the border is drawn outside and produced 32 + 2 + 2; measured,
	# the slots came out 30x30 against the PWA's 36.
	const POTION := 36.0
	const POTION_BORDER := 2.0
	for i in slots.size():
		var button := _make_slot_button("", Vector2(POTION, POTION))
		button.add_theme_stylebox_override("normal", _potion_style(POTION_BORDER))
		button.add_theme_stylebox_override("pressed", _potion_style(POTION_BORDER))
		var item_id: Variant = slots[i]
		var item: Dictionary = {} if item_id == null else _resolve(item_id)
		if item.is_empty():
			_set_placeholder_icon(button, "assets/items/potion_healing_light.png", 0.25)
		else:
			_set_placeholder_icon(button, str(item.get("iconImg", "")), 1.0)
		button.pressed.connect(func(): potion_slot_tapped.emit(i))
		_potion_nodes.append(button)
		_potion_row.add_child(button)


## `.inv-potion-slot { background:#000; border:2px solid #4a4a4a; border-radius:4px }` and
## `.empty { border-color:#3a3a3a; border-style:dashed }`. Godot draws a Button's stylebox
## around its content box, so a 2px border on a 32px minimum gives the PWA's 36 total.
func _potion_style(border: float) -> StyleBoxFlat:
	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#3a3a3a")
	style.set_border_width_all(int(border))
	style.set_corner_radius_all(4)
	return style


func _refresh_bag() -> void:
	# Rebuild, like the chest does. `UIKit.item_cell` is the ONE definition of a
	# `.chest-cell`, so the bag cannot drift from the chest again.
	for child in _bag_grid.get_children():
		_bag_grid.remove_child(child)
		child.queue_free()
	_bag_nodes.clear()
	var inventory: Array = _state.inventory()
	for i in BAG_CELLS:
		var item: Dictionary = {}
		var count := 0
		if i < inventory.size():
			var entry: Variant = inventory[i]
			var item_id: String = entry.get("id", "") if entry is Dictionary else str(entry)
			item = _resolve(item_id)
			count = int(entry.get("count", 1)) if entry is Dictionary else 1
			if not item.is_empty() and count > 1:
				item = item.duplicate()
				item["count"] = count
		var cell := UIKit.item_cell(item, BAG_CELL)
		# `.inv-grid { grid-template-columns:repeat(5, 1fr) }` — five EQUAL columns that
		# fill the row. A GridContainer sizes each column to its widest child unless the
		# children expand, which is why the measured cells are all 62.8 and the last one
		# ends exactly at the wrap's inner edge.
		cell.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		# ⚠️  A `GridContainer` HANDS EVERY ROW ITS MINIMUM, so with the grid's own minimum
		# pinned to the PWA's 269 the extra 3px must be claimed by the CELLS or it stays
		# unused at the bottom: `SIZE_EXPAND_FILL` makes each cell take its row's share, and
		# the rows then land 68.8 apart (the PWA's pitch) instead of 68.0. Without it the
		# cells keep their 62.8 and the drift survives the minimum fix.
		cell.size_flags_vertical = Control.SIZE_EXPAND_FILL
		# A tap opens the item's info overlay (the PWA's `#invItemOverlay`); equipping is
		# the overlay's button, not the tap.
		var index := i
		cell.pressed.connect(func(): _on_bag_tapped(index))
		_bag_nodes.append(cell)
		_bag_grid.add_child(cell)


## The PWA's tap routing on a bag cell: it does NOT equip. It selects the cell, marks it
## `.selected` and opens `#invItemOverlay` — the equipping happens from the overlay's own
## button, and a tap on the dim or the X clears the selection. The port equipped straight
## from the tap, which is why stats and compare had nowhere to appear.
##
## `_on_bag_tapped` is also driven by `_refresh_bag`'s own signal, so the two entry points
## (a fresh tap and the router's fallback) cannot drift.
func _on_bag_tapped(index: int) -> void:
	var inventory: Array = _state.inventory()
	if index < 0 or index >= inventory.size():
		close_item_info()
		return
	var entry: Variant = inventory[index]
	var item_id: String = str(entry.get("id", "")) if entry is Dictionary else str(entry)
	var item: Dictionary = _resolve(item_id)
	if item.is_empty():
		close_item_info()
		return
	# A different host invalidates the armed socket index.
	if _socket_host_id != item_id:
		_armed_socket = -1
		_socket_host_id = item_id
	_select_bag(index)
	_item_overlay.show_for_bag(item, index)
	item_tapped.emit(index)


## Tapping an EQUIP slot shows that item's info with an Unequip button; tapping the SAME
## slot again takes it off. That is the PWA's own two-step (`_invSelectedSlot`), and it is
## why one tap does not silently remove a piece of gear.
func _on_equip_slot_pressed(slot: String) -> void:
	var held: Variant = _state.equip().get(slot)
	var item_id: String = "" if held == null else str(held)
	# 'fists' is the implicit weapon: the slot reads as empty even though the id is set.
	if item_id == "" or item_id == "fists":
		close_item_info()
		equip_slot_tapped.emit(slot)
		return
	if _item_overlay.visible and _item_overlay.origin() == "equipped" 			and _item_overlay.origin_slot() == slot:
		close_item_info()
		equip_slot_tapped.emit(slot)
		return
	_select_slot(slot)
	_socket_host_id = item_id
	_armed_socket = -1
	_item_overlay.show_for_equipped(_resolve(item_id), slot)


func close_item_info() -> void:
	_item_overlay.close()


func _on_overlay_dismissed() -> void:
	_socket_host_id = ""
	_armed_socket = -1
	_clear_selection()


## `.chest-cell.selected { border-color:#f1c40f !important }` — the tap feedback the PWA
## gives the cell it just opened. One selection at a time, across both grids.
func _select_bag(index: int) -> void:
	for i in _bag_nodes.size():
		var cell: Button = _bag_nodes[i]
		if i == index:
			_set_border(cell, Color("#f1c40f"))
		elif i < _state.inventory().size():
			_set_border(cell, _quality_color(_cell_item(i)))
		else:
			cell.add_theme_stylebox_override("normal", _empty_bag_style())
	_clear_slot_selection_visuals()
	_selected_bag = index
	_selected_slot = ""


func _select_slot(slot: String) -> void:
	# First undo the previous selection (bag OR slot), then paint the new one gold.
	_selected_bag = -1
	if _selected_slot != "" and _slot_nodes.has(_selected_slot):
		_restore_slot_visual(_selected_slot)
	if _selected_slot != slot:
		pass
	for name in _slot_nodes:
		if name != slot:
			_restore_slot_visual(name)
	if _slot_nodes.has(slot):
		_set_border(_slot_nodes[slot], Color("#f1c40f"))
	_selected_slot = slot


## Put every cell and slot back to its own quality colour — the PWA's `clearSelection()`.
func _clear_selection() -> void:
	_selected_bag = -1
	_selected_slot = ""
	for name in _slot_nodes:
		_restore_slot_visual(name)
	for i in _bag_nodes.size():
		_restore_bag_visual(i)


## A slot back to its own colour (quality when filled, the empty style when not).
func _restore_slot_visual(slot: String) -> void:
	if not _slot_nodes.has(slot):
		return
	var button: Button = _slot_nodes[slot]
	var held: Variant = _state.equip().get(slot)
	var held_id: String = "" if held == null else str(held)
	if held_id == "" or held_id == "fists":
		button.add_theme_stylebox_override("normal", _empty_slot_style())
		button.add_theme_stylebox_override("pressed", _empty_slot_style())
	else:
		_set_border(button, _quality_color(_resolve(held_id)))


func _restore_bag_visual(index: int) -> void:
	if index < 0 or index >= _bag_nodes.size():
		return
	var cell: Button = _bag_nodes[index]
	var item := _cell_item(index)
	if item.is_empty():
		cell.add_theme_stylebox_override("normal", _empty_bag_style())
	else:
		_set_border(cell, _quality_color(item))


## Undo the gold selection on the cell the overlay was opened from — kept as its own
## function because BOTH `_select_bag` and `_select_slot` have to undo the other one.
func _clear_slot_selection_visuals() -> void:
	for name in _slot_nodes:
		_restore_slot_visual(name)


func _cell_item(index: int) -> Dictionary:
	var inventory: Array = _state.inventory()
	if index < 0 or index >= inventory.size():
		return {}
	var entry: Variant = inventory[index]
	var item_id: String = str(entry.get("id", "")) if entry is Dictionary else str(entry)
	return _resolve(item_id)


## The item the overlay is showing, or {} when it is closed. The router reads this to
## decide what an overlay button means without keeping a second copy of the selection.
func shown_item() -> Dictionary:
	return _item_overlay._item if _item_overlay != null else {}


func shown_item_id() -> String:
	return _item_overlay.current_item_id() if _item_overlay != null else ""


## The socket panel lives inside the overlay now: tapping a socket cell arms it, and the
## gems in the bag are listed under it. Both are re-rendered from the overlay's own
## `socket_armed`/`gem_tapped` signals.
func _refresh_sockets() -> void:
	if _item_overlay != null:
		_item_overlay.refresh_sockets(_socket_host_id, _armed_socket, _state.inventory())


## The panel's socket row was tapped: arm it (only an empty one is armable) and let the
## router validate against the socketing rules.
func _on_socket_cell_tapped(index: int) -> void:
	_armed_socket = index
	socket_armed.emit(_socket_host_id, index)


## A gem cell in the overlay was tapped.
func _on_gem_cell_tapped(gem_id: String) -> void:
	gem_tapped.emit(_socket_host_id, gem_id)


func _empty_bag_style() -> StyleBoxFlat:
	return UIKit.item_cell({}, BAG_CELL, false).get_theme_stylebox("normal")


func _empty_slot_style() -> StyleBoxFlat:
	var style := StyleBoxFlat.new()
	style.bg_color = Color("#000000")
	style.border_color = Color("#3a3a3a")
	style.set_border_width_all(int(SLOT_BORDER))
	style.set_corner_radius_all(8)
	style.set_content_margin_all(0)
	return style



func _set_slot_content(button: Button, item: Dictionary, placeholder: String, is_empty: bool) -> void:
	for child in button.get_children():
		child.queue_free()

	if item.is_empty():
		_set_empty_style(button)
		if placeholder != "":
			_set_placeholder_icon(button, placeholder, 0.25)
		return

	var icon := _slot_icon(button, ItemStats.icon_path(item))
	icon.modulate = Color(1, 1, 1, 1)
	_set_border(button, _quality_color(item))


func _set_placeholder_icon(button: Button, path: String, alpha: float) -> void:
	var icon := _slot_icon(button, path)
	icon.modulate = Color(1, 1, 1, alpha)


## A TextureRect filling a slot's CONTENT box — the Button's rect inset by the border —
## drawing the item icon the way the PWA's `<img>` does: `width:100%; height:100%;
## object-fit:contain; background:#000`.
##
## `STRETCH_KEEP_ASPECT_CENTERED` IS the CSS `object-fit:contain`, and it is what the live
## PWA uses (measured: `fit: "contain"` on every slot's `<img>`, from the inline style
## `renderItemIcon` writes — the `object-fit:cover` in `style.css` is overridden by it).
## So a square 256px icon in a 73x108 slot renders 73x73 centred in a black band, in both.
func _slot_icon(button: Button, path: String) -> TextureRect:
	var icon := TextureRect.new()
	icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	icon.offset_left = SLOT_BORDER
	icon.offset_top = SLOT_BORDER
	icon.offset_right = -SLOT_BORDER
	icon.offset_bottom = -SLOT_BORDER
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.texture = _load_texture(path)
	icon.mouse_filter = Control.MOUSE_FILTER_IGNORE
	button.add_child(icon)
	return icon


## Stack size badge, bottom-right, gold border — the PWA's `.cell-count`.
func _set_border(button: Button, colour: Color) -> void:
	var style: StyleBoxFlat = button.get_theme_stylebox("normal").duplicate()
	style.border_color = colour
	button.add_theme_stylebox_override("normal", style)
	button.add_theme_stylebox_override("pressed", style)
	button.add_theme_stylebox_override("hover", style)
	button.add_theme_stylebox_override("focus", style)


## Quality colour: unique and crafted override the plain quality string, matching
## getQualityColor() in the PWA.
func _quality_color(item: Dictionary) -> Color:
	if item.get("unique", false):
		return Color("#b8860b")
	if item.get("crafted", false):
		return Color("#ff8c00")
	var q: String = str(item.get("quality", item.get("rarity", "normal")))
	return QUALITY_FALLBACK.get(q, QUALITY_FALLBACK["normal"])


# --- resolvers ---------------------------------------------------------------

## An item id can be a static base (ITEMS), a generated gem, or a generated loot item
## on the save. All three must resolve, in that order of likelihood.
func _resolve(item_id: String) -> Dictionary:
	if item_id == "":
		return {}
	var static_item: Dictionary = _data.item(item_id)
	if not static_item.is_empty():
		return static_item
	# Gems are registered into the same index by game_data, so the lookup above
	# already covers them; anything left is a generated loot item.
	return _state.loot_item(item_id)


func _find_item_callable() -> Callable:
	return func(id): return _resolve(str(id))


func _load_texture(path: String) -> Texture2D:
	if path == "":
		return null
	var full := path if path.begins_with("res://") else "res://" + path
	if not ResourceLoader.exists(full):
		return null
	return load(full)
