extends Control
class_name InventoryScreen
## InventoryScreen — the character sheet: equipment slots, belt potions, bag grid.
##
## Built in code rather than as a .tscn because the PWA's inventory was generated by
## 842 lines of string concatenation: the layout is driven entirely by DATA (how many
## belt rows the worn belt has, how many gem stacks exist), so a hand-authored scene
## would have to rebuild itself anyway. Code-built means one source of truth.
##
## Design rules taken from the PWA and Jan's stated preferences:
##   - flat, machine-like design: no cards, no rounded panels, no shadows
##   - NO hover/focus states — mobile game, state only on tap
##   - no emoji: every slot renders a real PNG from assets/items/
##   - slot borders carry the item's quality colour

const GameData := preload("res://scripts/data/game_data.gd")
const ItemGen := preload("res://scripts/items/item_gen.gd")

const CELL := 64
const GRID_COLUMNS := 5
const BAG_CELLS := 20

## Slot order and labels for the equipment panel. The label is what the empty slot
## shows; the icon underneath is the "placeholder" PNG the PWA used per slot.
const SLOT_LABELS := {
	"weapon": "Main Hand", "armor": "Armor", "helmet": "Helmet", "shield": "Off Hand",
	"ring1": "Ring 1", "ring2": "Ring 2", "amulet": "Amulet", "belt": "Belt",
	"gloves": "Gloves", "boots": "Boots",
}

const SLOT_PLACEHOLDER := {
	"weapon": "assets/items/weapon_iron_sword.png",
	"armor": "assets/items/armor_leather.png",
	"helmet": "assets/items/helmet_linen_hood.png",
	"shield": "assets/items/shield_wooden.png",
	"ring1": "assets/items/ring_copper.png",
	"ring2": "assets/items/ring_copper.png",
	"amulet": "assets/items/amulet_bone.png",
	"belt": "assets/items/belt_cloth.png",
	"gloves": "assets/items/gloves_leather.png",
	"boots": "assets/items/boots_boots.png",
}

## Quality colours, from the RARITY table. Unique is checked first because a unique
## item also has quality 'unique'; crafted overrides everything.
const QUALITY_FALLBACK := {
	"normal": Color("#888888"), "magic": Color("#4a7dff"),
	"rare": Color("#ffd700"), "unique": Color("#b8860b"),
}

signal item_tapped(inventory_index: int)
signal equip_slot_tapped(slot: String)
signal potion_slot_tapped(index: int)
signal back_pressed()

var _data: Node
var _gen: ItemGen
var _state

var _slot_nodes: Dictionary = {}     # slot name -> Button
var _bag_nodes: Array = []           # Button per bag cell
var _potion_nodes: Array = []
var _bag_grid: GridContainer
var _potion_row: HBoxContainer
var _stats_label: Label


func _init(game_data: Node, gen: ItemGen, state) -> void:
	_data = game_data
	_gen = gen
	_state = state


func _ready() -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
	_build()
	refresh()


# --- construction ------------------------------------------------------------

func _build() -> void:
	var root := VBoxContainer.new()
	root.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.add_theme_constant_override("separation", 8)
	add_child(root)

	root.add_child(_make_header())

	var columns := HBoxContainer.new()
	columns.add_theme_constant_override("separation", 16)
	columns.size_flags_vertical = Control.SIZE_EXPAND_FILL
	root.add_child(columns)

	columns.add_child(_make_equipment_panel())
	columns.add_child(_make_bag_panel())


func _make_header() -> Control:
	var header := HBoxContainer.new()
	header.add_theme_constant_override("separation", 8)

	var back := Button.new()
	back.text = "Back to Town"
	back.custom_minimum_size = Vector2(160, 44)
	# Plain "Back to Town", no arrow — a convention Jan set for every full-page screen.
	back.pressed.connect(func(): back_pressed.emit())
	header.add_child(back)

	var title := Label.new()
	title.text = "Inventory"
	title.add_theme_font_size_override("font_size", 22)
	title.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	header.add_child(title)

	return header


func _make_equipment_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 6)

	var grid := GridContainer.new()
	grid.columns = 2
	grid.add_theme_constant_override("h_separation", 6)
	grid.add_theme_constant_override("v_separation", 6)
	panel.add_child(grid)

	for slot in ItemGen.EQUIP_SLOTS:
		var button := _make_slot_button(SLOT_LABELS.get(slot, slot))
		button.pressed.connect(func(): equip_slot_tapped.emit(slot))
		_slot_nodes[slot] = button
		grid.add_child(button)

	_stats_label = Label.new()
	_stats_label.add_theme_font_size_override("font_size", 13)
	_stats_label.add_theme_color_override("font_color", Color("#aaaaaa"))
	panel.add_child(_stats_label)

	var potion_title := Label.new()
	potion_title.text = "Belt"
	potion_title.add_theme_font_size_override("font_size", 14)
	panel.add_child(potion_title)

	_potion_row = HBoxContainer.new()
	_potion_row.add_theme_constant_override("separation", 4)
	panel.add_child(_potion_row)

	return panel


func _make_bag_panel() -> Control:
	var panel := VBoxContainer.new()
	panel.add_theme_constant_override("separation", 6)

	var title := Label.new()
	title.text = "Bag"
	title.add_theme_font_size_override("font_size", 14)
	panel.add_child(title)

	_bag_grid = GridContainer.new()
	_bag_grid.columns = GRID_COLUMNS
	_bag_grid.add_theme_constant_override("h_separation", 4)
	_bag_grid.add_theme_constant_override("v_separation", 4)
	panel.add_child(_bag_grid)

	for i in BAG_CELLS:
		var button := _make_slot_button("")
		button.pressed.connect(func(): item_tapped.emit(i))
		_bag_nodes.append(button)
		_bag_grid.add_child(button)

	return panel


## A slot is a flat square with a thin border. No rounded corners, no gradient, no
## hover state — tapping is the only feedback, which is what a mobile game wants and
## what Jan asked for explicitly.
func _make_slot_button(label: String) -> Button:
	var button := Button.new()
	button.custom_minimum_size = Vector2(CELL, CELL)
	button.flat = true
	button.focus_mode = Control.FOCUS_NONE   # no focus ring on tap
	button.mouse_filter = Control.MOUSE_FILTER_STOP

	var style := StyleBoxFlat.new()
	style.bg_color = Color("#111111")
	style.border_color = Color("#777777")
	style.set_border_width_all(1)
	style.corner_radius_top_left = 0
	style.corner_radius_top_right = 0
	style.corner_radius_bottom_left = 0
	style.corner_radius_bottom_right = 0
	button.add_theme_stylebox_override("normal", style)
	button.add_theme_stylebox_override("pressed", style)
	button.add_theme_stylebox_override("hover", style)
	button.add_theme_stylebox_override("focus", style)

	return button


# --- rendering ---------------------------------------------------------------

## Rebuild everything from the current save. Called after every mutation, which is
## how the PWA worked and keeps this function the single place that knows the layout.
func refresh() -> void:
	_refresh_equipment()
	_refresh_potions()
	_refresh_bag()
	_refresh_stats()


func _refresh_equipment() -> void:
	for slot in ItemGen.EQUIP_SLOTS:
		var button: Button = _slot_nodes[slot]
		var item_id: Variant = _state.equip().get(slot)
		# 'fists' is the implicit weapon: the slot reads as empty even though the id
		# is set, exactly as the PWA did.
		var is_empty: bool = item_id == null or item_id == "" or item_id == "fists"
		var item: Dictionary = {} if is_empty else _resolve(item_id)
		_set_slot_content(button, item, SLOT_PLACEHOLDER.get(slot, ""), is_empty)


func _refresh_potions() -> void:
	_state.sync_potion_slots(_find_item_callable())
	for child in _potion_row.get_children():
		child.queue_free()
	_potion_nodes.clear()

	var slots: Array = _state.equip().get("beltPotionSlots", [])
	for i in slots.size():
		var button := _make_slot_button("")
		button.custom_minimum_size = Vector2(40, 40)
		var item_id: Variant = slots[i]
		var item: Dictionary = {} if item_id == null else _resolve(item_id)
		if item.is_empty():
			# Empty potion slots show a desaturated potion icon, never an emoji.
			_set_placeholder_icon(button, "assets/items/potion_healing_light.png", 0.25)
		else:
			_set_slot_content(button, item, "", false)
		button.pressed.connect(func(): potion_slot_tapped.emit(i))
		_potion_nodes.append(button)
		_potion_row.add_child(button)


func _refresh_bag() -> void:
	var inventory: Array = _state.inventory()
	for i in BAG_CELLS:
		var button: Button = _bag_nodes[i]
		if i >= inventory.size():
			_set_slot_content(button, {}, "", true)
			continue
		var entry: Variant = inventory[i]
		var item_id: String = entry.get("id", "") if entry is Dictionary else str(entry)
		var count: int = int(entry.get("count", 1)) if entry is Dictionary else 1
		var item: Dictionary = _resolve(item_id)
		_set_slot_content(button, item, "", false)
		if count > 1:
			_add_count_badge(button, count)


func _refresh_stats() -> void:
	var hero: Dictionary = _state.hero()
	var find := _find_item_callable()
	var max_hp := _gen.hero_max_hp(hero, _state.equip(), find)
	var max_mana := _gen.hero_max_mana(hero, _state.equip(), _state.data.get("heroClass", ""), find)
	var attrs := _gen.equip_attr_sum(_state.equip(), find, ["str", "vit", "dex", "int"])
	_stats_label.text = "Level %d   HP %d   Mana %d   STR %d  VIT %d  DEX %d  INT %d   Gold %d" % [
		int(hero["level"]), max_hp, max_mana,
		int(hero.get("attrStr", 0)) + int(attrs["str"]),
		int(hero.get("attrVit", 0)) + int(attrs["vit"]),
		int(hero.get("attrDex", 0)) + int(attrs["dex"]),
		int(hero.get("attrInt", 0)) + int(attrs["int"]),
		int(hero.get("gold", 0)),
	]


## One slot's contents: an icon (or a dimmed placeholder when empty) and a border in
## the item's quality colour.
func _set_slot_content(button: Button, item: Dictionary, placeholder: String, is_empty: bool) -> void:
	for child in button.get_children():
		child.queue_free()

	if item.is_empty():
		if placeholder != "":
			_set_placeholder_icon(button, placeholder, 0.25)
		_set_border(button, Color("#777777"))
		return

	var icon := TextureRect.new()
	icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.texture = _load_texture(str(item.get("iconImg", "")))
	button.add_child(icon)
	_set_border(button, _quality_color(item))


func _set_placeholder_icon(button: Button, path: String, alpha: float) -> void:
	var icon := TextureRect.new()
	icon.set_anchors_preset(Control.PRESET_FULL_RECT)
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.texture = _load_texture(path)
	icon.modulate = Color(1, 1, 1, alpha)
	button.add_child(icon)


## Stack size badge, bottom-right, gold border — the PWA's `.cell-count`.
func _add_count_badge(button: Button, count: int) -> void:
	var badge := Label.new()
	badge.text = str(count)
	badge.add_theme_font_size_override("font_size", 11)
	badge.add_theme_color_override("font_color", Color("#f1c40f"))
	badge.position = Vector2(CELL - 24, CELL - 18)
	badge.custom_minimum_size = Vector2(22, 14)
	badge.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER

	var style := StyleBoxFlat.new()
	style.bg_color = Color("#111111")
	style.border_color = Color("#f1c40f")
	style.set_border_width_all(1)
	badge.add_theme_stylebox_override("normal", style)
	button.add_child(badge)


func _set_border(button: Button, colour: Color) -> void:
	var style: StyleBoxFlat = button.get_theme_stylebox("normal").duplicate()
	style.border_color = colour
	button.add_theme_stylebox_override("normal", style)
	button.add_theme_stylebox_override("pressed", style)
	button.add_theme_stylebox_override("hover", style)
	button.add_theme_stylebox_override("focus", style)


## Quality colour: unique and crafted override the plain quality string, matching
## getQualityColor() in the PWA.
func _quality_color(item: Dictionary) -> Color:
	if item.get("unique", false):
		return Color("#b8860b")
	if item.get("crafted", false):
		return Color("#ff8c00")
	var q: String = str(item.get("quality", item.get("rarity", "normal")))
	return QUALITY_FALLBACK.get(q, QUALITY_FALLBACK["normal"])


# --- resolvers ---------------------------------------------------------------

## An item id can be a static base (ITEMS), a generated gem, or a generated loot item
## on the save. All three must resolve, in that order of likelihood.
func _resolve(item_id: String) -> Dictionary:
	if item_id == "":
		return {}
	var static_item: Dictionary = _data.item(item_id)
	if not static_item.is_empty():
		return static_item
	# Gems are registered into the same index by game_data, so the lookup above
	# already covers them; anything left is a generated loot item.
	return _state.loot_item(item_id)


func _find_item_callable() -> Callable:
	return func(id): return _resolve(str(id))


func _load_texture(path: String) -> Texture2D:
	if path == "":
		return null
	var full := path if path.begins_with("res://") else "res://" + path
	if not ResourceLoader.exists(full):
		return null
	return load(full)
