extends RefCounted
## Bindable touch-button layout: four round buttons in a d-pad cross.
## Slot -> Input Map action. Persisted to user://controls.cfg so a player's
## remap survives restarts.
##
## Default cross: down = attack, up = potion, left = spell 1, right = spell 2.
## Attack sits at the bottom deliberately - that is where the thumb rests.

const CFG_PATH := "user://controls.cfg"
const SLOTS: Array[String] = ["up", "down", "left", "right"]

const DEFAULT_SLOTS := {
	"down": "attack",
	"up": "potion",
	"left": "skill_1",
	"right": "skill_2",
}

## Everything a button is allowed to carry. Keep in sync with the [input]
## section of project.godot (regenerated by tools/gen_input_map.gd).
const AVAILABLE: Array[String] = ["attack", "skill_1", "skill_2", "potion", "none"]

const LABELS := {
	"attack": "Útok",
	"skill_1": "Kouzlo 1",
	"skill_2": "Kouzlo 2",
	"potion": "Lektvar",
	"none": "—",
}

var slots: Dictionary = {}


func _init() -> void:
	slots = DEFAULT_SLOTS.duplicate()
	load_from_disk()


func action_for(slot: String) -> String:
	return str(slots.get(slot, "none"))


func label_for_slot(slot: String) -> String:
	return str(LABELS.get(action_for(slot), "?"))


func label_for_action(action: String) -> String:
	return str(LABELS.get(action, "?"))


func is_available(action: String) -> bool:
	return AVAILABLE.has(action)


func assign(slot: String, action: String) -> void:
	if not is_available(action) or not SLOTS.has(slot):
		return
	if action != "none":
		# One action = one button. If it already lives on another slot, the two
		# SWAP, so a remap can never leave the player with a dead button.
		for other in SLOTS:
			if other != slot and action_for(other) == action:
				slots[other] = action_for(slot)
				break
	slots[slot] = action
	save_to_disk()


func reset_to_defaults() -> void:
	slots = DEFAULT_SLOTS.duplicate()
	save_to_disk()


func save_to_disk() -> void:
	var cf := ConfigFile.new()
	for s in SLOTS:
		cf.set_value("touch", s, action_for(s))
	cf.save(CFG_PATH)


func load_from_disk() -> void:
	var cf := ConfigFile.new()
	if cf.load(CFG_PATH) != OK:
		return
	for s in SLOTS:
		var v: String = str(cf.get_value("touch", s, str(DEFAULT_SLOTS[s])))
		slots[s] = v if is_available(v) else str(DEFAULT_SLOTS[s])
